export const greekPrefixes: Record<number, string> = {
  1: 'Mono',
  2: 'Di',
  3: 'Tri',
  4: 'Tetra',
  5: 'Penta',
  6: 'Heksa',
  7: 'Hepta',
  8: 'Okta',
  9: 'Nona',
  10: 'Deka',
  11: 'Undeka',
  12: 'Dodeka',
  13: 'Trideka',
  14: 'Tetradeka',
  15: 'Pentadeka',
  16: 'Heksadeka',
  17: 'Heptadeka',
  18: 'Oktadeka',
  19: 'Nonadeka',
  20: 'Ikosa',
  21: 'Henikosa',
  22: 'Dokosa',
  23: 'Trikosa',
  24: 'Tetrakosa',
  25: 'Pentakosa',
  26: 'Heksakosa',
  27: 'Heptakosa',
  28: 'Oktakosa',
  29: 'Nonakosa',
  30: 'Triakonta',
  31: 'Hentriakonta',
  32: 'Dotriakonta',
  33: 'Tritriakonta',
  34: 'Tetratriakonta',
  35: 'Pentatriakonta',
  36: 'Heksatriakonta',
  37: 'Heptatriakonta',
  38: 'Oktatriakonta',
  39: 'Nonatriakonta',
  40: 'Tetrakonta',
  41: 'Hentetrakonta',
  42: 'Dotetrakonta',
  43: 'Tritetrakonta',
  44: 'Tetratetrakonta',
  45: 'Pentatetrakonta',
  46: 'Heksatetrakonta',
  47: 'Heptatetrakonta',
  48: 'Oktatetrakonta',
  49: 'Nonatetrakonta',
  50: 'Pentakonta'
}

export const getGreekPrefix = (count: number): string => {
  return greekPrefixes[count] || ''
}
